# Generated by Django 4.2 on 2023-06-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_deliverer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default='restaurants/default.png', upload_to='restaurants/%Y/%m/%d'),
        ),
    ]
