# Generated by Django 4.2.7 on 2024-05-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_remove_category_image_category_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menus_meals', to='coreapp.meal'),
            preserve_default=False,
        ),
    ]
