# Generated by Django 4.2.7 on 2024-05-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_menu_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='products',
        ),
        migrations.AddField(
            model_name='meal',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals_products', to='coreapp.product'),
            preserve_default=False,
        ),
    ]
