# Generated by Django 4.2.7 on 2024-05-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_remove_meal_products_meal_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='products',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='meals',
        ),
        migrations.AddField(
            model_name='meal',
            name='products',
            field=models.ManyToManyField(related_name='meals_products', to='coreapp.product'),
        ),
        migrations.AddField(
            model_name='menu',
            name='meals',
            field=models.ManyToManyField(related_name='menus_meals', to='coreapp.meal'),
        ),
    ]
