# Generated by Django 4.2.7 on 2024-05-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_alter_schedule_options_remove_user_is_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='schedule',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='schedule',
            field=models.ManyToManyField(related_name='restaurants_schedule', to='coreapp.schedule'),
        ),
    ]
