# Generated by Django 4.2.7 on 2024-05-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_remove_restaurant_schedule_restaurant_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_supply', to='coreapp.supplement'),
        ),
    ]
