# Generated by Django 4.2.7 on 2024-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0021_restaurant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
