# Generated by Django 4.2.7 on 2024-05-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0022_alter_address_google_place_id_alter_address_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='coreapp.category'),
        ),
    ]
