# Generated by Django 4.2.7 on 2024-05-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0024_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='tags',
        ),
    ]
