runtime: python39

instance_class: F2

entrypoint: gunicorn -b :$PORT restaurant.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: restaurant.settings_production
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  DB_CONNECTION_NAME: ${{ secrets.DB_CONNECTION_NAME }}
  GS_BUCKET_NAME: ${{ secrets.GS_BUCKET_NAME }}

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 1
