name: pre-commit

on:
  workflow_call:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/setup-python@v3
    - name: 'install terraform-docs'
      run: >
        curl -L
        "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest
        | grep -o -E -m 1 "https://.+?-linux-amd64.tar.gz")"
        > terraform-docs.tgz
        && tar -xzf terraform-docs.tgz terraform-docs
        && chmod +x terraform-docs
        && sudo mv terraform-docs /usr/bin/
    - uses: pre-commit/action@v3.0.1
